name: Fraser Valley Travel Clinic
favicon: null
layout_spectrum: 0.18564
typography_spectrum: 0.33416
title: 'Welcome to Our New Look - Changes Will Come Soon!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3deff'
    - '#040404'
    - '#36543a'
    - '#969c78'
    - '#d26934'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
