name: Fraser Valley Travel Clinic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66584
title: 'Welcome to Our New Look - Changes Will Come Soon!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81847d'
    - '#b2aea3'
    - '#1d1b1a'
    - '#b89400'
    - '#bc3326'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
