name: Fraser Valley Travel Clinic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9974136252421886
title: 'Welcome to Our New Look - Changes Will Come Soon!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe2e7'
    - '#2c2924'
    - '#00a7f0'
    - '#73815d'
    - '#00649c'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
